name: flutter_application
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # StateManagement
  flutter_bloc:
  tuple:
  freezed_annotation:
  # JsonParser
  json_annotation:

  # Http Client
  dio:

  #Svg Loader
  flutter_svg:

  # Local Persist
  shared_preferences:

  # Simple direct Service Locator
  get_it:

  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.0.0

  #auth_nav
  auth_nav:
    git: https://github.com/dangngocduc/auth_nav

  oauth2_dio:
    git: https://github.com/dangngocduc/oauth2_dio

  # Collections and utilities functions and classes related to collections.
  collection: 1.16.0

  smooth_page_indicator: 1.0.0+2

  google_fonts: 3.0.1

  readmore: ^2.2.0

  flutter_lorem: ^2.0.0

  expandable_text: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  flutter_lints:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.0

# Config icon application
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: geometric_415
      fonts:
        - asset: assets/fonts/geometric_415_black_bt.ttf
    - family: gill_sans_mt
      fonts:
        - asset: assets/fonts/gill_sans_mt.ttf
    - family: sf_ui_display
      fonts:
        - asset: assets/fonts/sf_ui_display_black.otf
          weight: 900
        - asset: assets/fonts/sf_ui_display_heavy.otf
          weight: 800
        - asset: assets/fonts/sf_ui_display_bold.otf
          weight: 600
        - asset: assets/fonts/sf_ui_display_semibold.otf
          weight: 500
        - asset: assets/fonts/sf_ui_display_medium.otf
          weight: 400
        - asset: assets/fonts/sf_ui_display_light.otf
          weight: 300
        - asset: assets/fonts/sf_ui_display_thin.otf
          weight: 200
        - asset: assets/fonts/sf_ui_display_ultralight.otf
          weight: 100



flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
